name = "JuliaTools"
uuid = "80295348-f033-4963-b505-92c8ebed806e"
authors = ["Benjamin Lozano <bllozano@uc.cl> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
